BUILD_DIR=$(pwd)"/../build/"
VISE_ROOTDIR=$(pwd)"/../"

if [ -d "$BUILD_DIR" ]; then
    rm -fr $BUILD_DIR
fi

mkdir $BUILD_DIR


FASTANN_LIBDIR=$VISE_ROOTDIR"dep/lib/fastann/"
IMAGEMAGICK_LIBDIR=$VISE_ROOTDIR"dep/lib/imagemagick/"
PROTOBUF_LIBDIR=$VISE_ROOTDIR"dep/lib/protobuf/"
BOOST_LIBDIR=$VISE_ROOTDIR"dep/lib/boost/"
VISE_CMAKE_PREFIX_PATH=$FASTANN_LIBDIR";"$IMAGEMAGICK_LIBDIR";"$PROTOBUF_LIBDIR

cd $BUILD_DIR
CC=gcc-5 CXX=g++-5 cmake -Wno-dev -DCMAKE_PREFIX_PATH=$VISE_CMAKE_PREFIX_PATH -DBOOST_ROOT=$BOOST_LIBDIR $VISE_ROOTDIR"src/"

make
export DYLD_FALLBACK_LIBRARY_PATH=$FASTANN_LIBDIR"lib/:"$PROTOBUF_LIBDIR"lib/:"$BOOST_LIBDIR"lib/"

v2/api/api_v2 35280 ox5k
