// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_db_header.proto

#ifndef PROTOBUF_proto_5fdb_5fheader_2eproto__INCLUDED
#define PROTOBUF_proto_5fdb_5fheader_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace rr {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_proto_5fdb_5fheader_2eproto();
void protobuf_AssignDesc_proto_5fdb_5fheader_2eproto();
void protobuf_ShutdownFile_proto_5fdb_5fheader_2eproto();

class protoDbHeader;

// ===================================================================

class protoDbHeader : public ::google::protobuf::Message {
 public:
  protoDbHeader();
  virtual ~protoDbHeader();

  protoDbHeader(const protoDbHeader& from);

  inline protoDbHeader& operator=(const protoDbHeader& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const protoDbHeader& default_instance();

  void Swap(protoDbHeader* other);

  // implements Message ----------------------------------------------

  protoDbHeader* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const protoDbHeader& from);
  void MergeFrom(const protoDbHeader& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint64 offset = 1 [packed = true];
  inline int offset_size() const;
  inline void clear_offset();
  static const int kOffsetFieldNumber = 1;
  inline ::google::protobuf::uint64 offset(int index) const;
  inline void set_offset(int index, ::google::protobuf::uint64 value);
  inline void add_offset(::google::protobuf::uint64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      offset() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_offset();

  // optional string description = 2;
  inline bool has_description() const;
  inline void clear_description();
  static const int kDescriptionFieldNumber = 2;
  inline const ::std::string& description() const;
  inline void set_description(const ::std::string& value);
  inline void set_description(const char* value);
  inline void set_description(const char* value, size_t size);
  inline ::std::string* mutable_description();
  inline ::std::string* release_description();
  inline void set_allocated_description(::std::string* description);

  // @@protoc_insertion_point(class_scope:rr.protoDbHeader)
 private:
  inline void set_has_description();
  inline void clear_has_description();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > offset_;
  mutable int _offset_cached_byte_size_;
  ::std::string* description_;
  friend void  protobuf_AddDesc_proto_5fdb_5fheader_2eproto();
  friend void protobuf_AssignDesc_proto_5fdb_5fheader_2eproto();
  friend void protobuf_ShutdownFile_proto_5fdb_5fheader_2eproto();

  void InitAsDefaultInstance();
  static protoDbHeader* default_instance_;
};
// ===================================================================


// ===================================================================

// protoDbHeader

// repeated uint64 offset = 1 [packed = true];
inline int protoDbHeader::offset_size() const {
  return offset_.size();
}
inline void protoDbHeader::clear_offset() {
  offset_.Clear();
}
inline ::google::protobuf::uint64 protoDbHeader::offset(int index) const {
  // @@protoc_insertion_point(field_get:rr.protoDbHeader.offset)
  return offset_.Get(index);
}
inline void protoDbHeader::set_offset(int index, ::google::protobuf::uint64 value) {
  offset_.Set(index, value);
  // @@protoc_insertion_point(field_set:rr.protoDbHeader.offset)
}
inline void protoDbHeader::add_offset(::google::protobuf::uint64 value) {
  offset_.Add(value);
  // @@protoc_insertion_point(field_add:rr.protoDbHeader.offset)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
protoDbHeader::offset() const {
  // @@protoc_insertion_point(field_list:rr.protoDbHeader.offset)
  return offset_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
protoDbHeader::mutable_offset() {
  // @@protoc_insertion_point(field_mutable_list:rr.protoDbHeader.offset)
  return &offset_;
}

// optional string description = 2;
inline bool protoDbHeader::has_description() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void protoDbHeader::set_has_description() {
  _has_bits_[0] |= 0x00000002u;
}
inline void protoDbHeader::clear_has_description() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void protoDbHeader::clear_description() {
  if (description_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    description_->clear();
  }
  clear_has_description();
}
inline const ::std::string& protoDbHeader::description() const {
  // @@protoc_insertion_point(field_get:rr.protoDbHeader.description)
  return *description_;
}
inline void protoDbHeader::set_description(const ::std::string& value) {
  set_has_description();
  if (description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    description_ = new ::std::string;
  }
  description_->assign(value);
  // @@protoc_insertion_point(field_set:rr.protoDbHeader.description)
}
inline void protoDbHeader::set_description(const char* value) {
  set_has_description();
  if (description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    description_ = new ::std::string;
  }
  description_->assign(value);
  // @@protoc_insertion_point(field_set_char:rr.protoDbHeader.description)
}
inline void protoDbHeader::set_description(const char* value, size_t size) {
  set_has_description();
  if (description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    description_ = new ::std::string;
  }
  description_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:rr.protoDbHeader.description)
}
inline ::std::string* protoDbHeader::mutable_description() {
  set_has_description();
  if (description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    description_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:rr.protoDbHeader.description)
  return description_;
}
inline ::std::string* protoDbHeader::release_description() {
  clear_has_description();
  if (description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = description_;
    description_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void protoDbHeader::set_allocated_description(::std::string* description) {
  if (description_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete description_;
  }
  if (description) {
    set_has_description();
    description_ = description;
  } else {
    clear_has_description();
    description_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:rr.protoDbHeader.description)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace rr

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_5fdb_5fheader_2eproto__INCLUDED
